#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
# This is a placeholder. Run `gradle wrapper` locally to generate the full wrapper.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is an empty place holder. The real gradle wrapper jar is required.
echo "ERROR: gradle-wrapper.jar is missing."
echo "Please run 'gradle wrapper' in this project directory to generate the wrapper files."
exit 1
